# Generated by Django 3.1.3 on 2023-05-11 01:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.RemoveField(
            model_name='question',
            name='grade_point',
        ),
        migrations.RemoveField(
            model_name='question',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='chocies',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='courses',
            field=models.ManyToManyField(to='onlinecourse.Course'),
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='This is a sample question.', max_length=500),
        ),
        migrations.AddField(
            model_name='submission',
            name='choices',
            field=models.ManyToManyField(to='onlinecourse.Choice'),
        ),
        migrations.AddField(
            model_name='submission',
            name='date_submitted',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlinecourse.question'),
        ),
    ]
